## Image filtering

In [111]:
using ImageFiltering, TestImages

### 2D image

In [112]:
image_size = (7,7)

# Create a two-dimensional discrete unit impulse function.
f = fill(0,image_size);
f[4, 4] = 1;
f

7×7 Matrix{Int64}:
 0  0  0  0  0  0  0
 0  0  0  0  0  0  0
 0  0  0  0  0  0  0
 0  0  0  1  0  0  0
 0  0  0  0  0  0  0
 0  0  0  0  0  0  0
 0  0  0  0  0  0  0

Apply a mask

In [113]:
# Specify a filter coefficient mask and set the center of the mask as the origin.
w = centered([1 2 3; 4 5 6 ; 7 8 9];)

3×3 OffsetArray(::Matrix{Int64}, -1:1, -1:1) with eltype Int64 with indices -1:1×-1:1:
 1  2  3
 4  5  6
 7  8  9

Convolve

In [114]:
convolution = imfilter(f,reflect(w), Fill(0,w))

7×7 Matrix{Int64}:
 0  0  0  0  0  0  0
 0  0  0  0  0  0  0
 0  0  1  2  3  0  0
 0  0  4  5  6  0  0
 0  0  7  8  9  0  0
 0  0  0  0  0  0  0
 0  0  0  0  0  0  0

In [115]:
correlation = imfilter(f,w,Fill(0,w))

7×7 Matrix{Int64}:
 0  0  0  0  0  0  0
 0  0  0  0  0  0  0
 0  0  9  8  7  0  0
 0  0  6  5  4  0  0
 0  0  3  2  1  0  0
 0  0  0  0  0  0  0
 0  0  0  0  0  0  0

### Median Filters
The Median filter is the popular known order-statistic filter in digital image processing. Median filter is very popular technique for the removal of impulse noise because of its good de-noising power and mathematical accuracy. The value of a pixel is replaced by a median of the intensity levels in the neighborhood of that pixel by the Median Filter. A fixed filtering window size is used for outcome of neighborhood pixels by the Median Filter. The median filters are implemented consistently across the image and therefore tends to modify both noisy and noise free pixels present in the image. Relation to this, there is always a chance of replacement of good pixels by some corrupted ones. Therefore, de-noising is often accomplished at the expense of blurred and distorted features thus removing fine details present in the image.

In [116]:
using Statistics
median_filetr_size = (3,3)
imgm = mapwindow(median, f, median_filetr_size)

7×7 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0

### Gaussian filter
Gaussian Noise which is added to the images shown in the fig 6(a).Gaussian distribution which is also known as normal distribution whose probability is equal to statistical noise known as Gaussian Noise. Due to poor illumination and great extent of temperature or transmission of particles in an electronic image it fails to meet up the requirement for the clear image this noise is caused. By using a Weiner filter this noise can be reduced to very much extent. Same filters are used to check out the best filter for this noise. The best filter was Weiner filter but the minimum size value after using the different filters is given by all three filters shown in fig 5. Each filter is used on all the images, their outcome is noted and compared with the other entire filter applied on the same images. The circularly symmetric Gaussian behavior is found in the mellow ultra- sound speckle echo for marginal statistics which is similar to the laser speckle for monochromatic illumination.

In [117]:
σₓ = 0.5
lₓ = 5
σᵧ = 0.5
lᵧ = 5
gaussian_kernel = KernelFactors.gaussian((σₓ,σᵧ), (lₓ,lᵧ))
filtered_gaussian_image = imfilter(f,gaussian_kernel,Fill(0))

7×7 Matrix{Float64}:
 0.0  0.0          0.0         0.0          0.0         0.0          0.0
 0.0  6.96248e-8   2.80886e-5  0.000207549  2.80886e-5  6.96248e-8   0.0
 0.0  2.80886e-5   0.0113318   0.0837311    0.0113318   2.80886e-5   0.0
 0.0  0.000207549  0.0837311   0.618694     0.0837311   0.000207549  0.0
 0.0  2.80886e-5   0.0113318   0.0837311    0.0113318   2.80886e-5   0.0
 0.0  6.96248e-8   2.80886e-5  0.000207549  2.80886e-5  6.96248e-8   0.0
 0.0  0.0          0.0         0.0          0.0         0.0          0.0

## 3D image

In [118]:
image_size = (3,3,3)

# Create a two-dimensional discrete unit impulse function.
f = fill(0,image_size);
f[2, 2, 2] = 1;
f

3×3×3 Array{Int64, 3}:
[:, :, 1] =
 0  0  0
 0  0  0
 0  0  0

[:, :, 2] =
 0  0  0
 0  1  0
 0  0  0

[:, :, 3] =
 0  0  0
 0  0  0
 0  0  0

In [119]:
# Specify a filter coefficient mask and set the center of the mask as the origin.
w = zeros(3,3,3)
w_f = [1 2 3; 4 5 6 ; 7 8 9]
w[:,:,1] = w_f
w[:,:,2] = w_f
w[:,:,3] = w_f
w

3×3×3 Array{Float64, 3}:
[:, :, 1] =
 1.0  2.0  3.0
 4.0  5.0  6.0
 7.0  8.0  9.0

[:, :, 2] =
 1.0  2.0  3.0
 4.0  5.0  6.0
 7.0  8.0  9.0

[:, :, 3] =
 1.0  2.0  3.0
 4.0  5.0  6.0
 7.0  8.0  9.0

In [120]:
correlation = imfilter(f,w, Fill(0))

3×3×3 Array{Float64, 3}:
[:, :, 1] =
 9.0  8.0  7.0
 6.0  5.0  4.0
 3.0  2.0  1.0

[:, :, 2] =
 9.0  8.0  7.0
 6.0  5.0  4.0
 3.0  2.0  1.0

[:, :, 3] =
 9.0  8.0  7.0
 6.0  5.0  4.0
 3.0  2.0  1.0